language: java
jdk: oraclejdk8
sudo: required
services:
- docker
script:
- "./gradlew clean check jacocoTestReport stage"
- docker build -t therickys93/wikiserver .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker push therickys93/wikiserver;
  fi
