version: '2'

services:
  redis:
    image: therickys93/wikiredis
    restart: always
    volumes:
      - redis_database:/data
    networks:
      - backbone

  controller:
    image: therickys93/wikicontroller
    restart: always
    environment:
      - "HOST=redis"
    networks:
      - backbone

  data:
    image: therickys93/wikidata
    environment:
        # - FTP_SERVER=<your_server>
        # - FTP_USERNAME=<your_username>
        # - FTP_PASSWORD=<your_password>
        - REDIS=redis
        - POSTGRES=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=wiki
        # - DROPBOX=<any_string>
        # - DROPBOX_ACCESS_TOKEN=<your_access_token>
    networks: 
        - backbone

  proxy:
    image: therickys93/wikiproxy
    restart: always
    ports:
      - "80:80"
    networks:
      - backbone

  postgres:
    image: therickys93/wikidatabase
    restart: always
    environment:
     - POSTGRES_PASSWORD=example
    volumes:
     - postgresql_database:/var/lib/postgresql/data
    networks:
     - backbone

  server:
    build: .
    restart: always
    environment:
      - WIKISERVER_PORT=8080
      - WIKISERVER_HOST=localhost
      - WIKISERVER_WOEID=716231
      - WIKISERVER_DB_HOST=postgres
      - WIKISERVER_DB_PORT=5432
      - WIKISERVER_DB_DATABASE=wiki
      - WIKISERVER_CONTROLLER_URL=http://controller:3000
    ports:
      - "8080:8080"
    networks:
      - backbone

volumes:
  postgresql_database:
    driver: local
  redis_database:
    driver: local

networks:
  backbone:
    driver: bridge
